config/routes.rb
SouthPortSite2::Application.routes.draw do

  root "home#index"
  get "notifications/index"
  get "about", to: 'about#index'
  get "links", to: 'links#index'
  get "links/test", to: 'links#test'
  get "helpful", to: 'helpful#index'
  get "events", to: 'events#index'

  get '/map', to: 'info#map' 
  get '/infolist/:entityName', to: 'info#index' 
  get '/institution', to: 'info#institution', as: :institution
  get '/info/:entityName/:entityId', to: 'info#institution_page', as: :institution_page
  get "notifications", to: 'notifications#index'

  resources :articles, only: [:show, :index]

  resources :comments, only: [:create, :edit, :update, :destroy]

  resources :events

  get "users_profile/:id", to: 'users_profile#show', as: :user

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  namespace :admin do
    resources :articles
    patch '/articles/:id/set_approved', to: 'articles#set_approved', as: :article_set_approved
  end

  post '/tinymce_assets' => 'tinymce_assets#create'

  get "test/index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  has_attached_file :picture, 
    styles: { medium: "400x400>"}, 
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :picture, 
    content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def html_text
    text.gsub("\n", "<br/>").html_safe
  end

  def initialize(args=nil)
    super
    self.date = Time.now
    self.votes = 0
  end

  def add_notification(path, user)
    if commentable.respond_to? :add_notification
      commentable.add_notification(self, path, user)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, only: [:create]
  # GET /comments/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        path = owner_path(@comment, true)
        @comment.add_notification(path, current_user)
        format.html { redirect_to path }
        format.json { render action: 'show', status: :created, location: @comment }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if params[:button] == 'cancel' || @comment.update(comment_params)
        format.html { redirect_to owner_path(@comment, true), notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to owner_path(@comment) }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      p = params.require(:comment)
        .permit(:text, :commentable_id, :commentable_type, :picture)
      p[:user_id] = current_user.id
      p
    end

    def owner_path(comment, with_key = false)
      url = comment.commentable.try :url
      url ||= request.referrer
      url += "#comment_" + comment.id.to_s if with_key
      url
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.comment.editable{ id: "comment_#{comment.id}" }
  %span.user-link 
    %a{ href: user_path(comment.user), class: 'nickname' }= comment.user.nickname
  %text.comment_text= comment.html_text
  - if comment.user == current_user
    %span.comment_action
      = link_to '', edit_comment_path(comment), class: 'comment_change', remote: true
      = link_to '', comment_path(comment), method: :delete, class: 'comment_delete', remote: true, data: { confirm: 'Вы уверены?' }
  - if comment.picture?
    = link_to image_tag(comment.picture.url(:medium), class: 'comment_image'), comment.picture.url
  .footer 
    = time_ago_in_words comment.date
    назад
      

app/views/comments/_comments_panel.html.haml
.comments-panel
  -cmts = owner.comments
  .comments-info 
    %span#comments_count= comments(cmts.count)
  .line 
  .comments
    = render partial: 'comments/comment', collection: cmts.order("date")
  .comment_form
    - if current_user
      = render partial: 'comments/form', locals: { owner: owner }

app/views/comments/_form.html.haml
- @comment ||= Comment.new
= form_for(@comment, remote: true, html: { multipart: true }) do |f|
  = f.text_area :text, class: "comment_text_field", rows: 10, cols: 70, placeholder: 'Добавить комментарий...'
  %img#picture_button{ src: image_path('photo.png') }
  = f.file_field :picture, id: 'hidden_picture_button'
  %span#filename
  = f.hidden_field :commentable_id, value: owner.id
  = f.hidden_field :commentable_type, value: owner.class.model_name.name

  = f.button 'Отмена' , class: 'hidden_cancel', value: 'cancel'
  = f.submit @comment.persisted? ? 'Применить' : 'Добавить комментарий', class: 'hidden_submit'

app/views/comments/create.js.erb
var comments = $('.comments');
comments.append("<%= j render partial: 'comments/comment', object: @comment %>");

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();
$('#comments_count').text('<%= j comments(Page.work.comments.count) %>');

app/views/comments/edit.html.haml
%h1 Изменение коментария

= render partial: 'comments/form', locals: { owner: @comment.commentable}

= link_to 'Вернуться', comments_path

app/views/comments/edit.js.erb
var text = $('#comment_<%= @comment.id %> .comment_text');
text.replaceWith("<%= j render partial: 'comments/form', locals: { owner: Page.work } %>");
$('.hidden_submit').hide();
// $('.hidden_cancel').hide();

var c = $('#comment_<%= @comment.id %>');
c.removeClass('editable');

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Date:</strong>
  <%= @comment.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @comment.votes %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/update.js.erb
var form = $('#edit_comment_<%= @comment.id %>');
form.replaceWith("<text class='comment_text'><%= @comment.html_text %> </text>");
var c = $('#comment_<%= @comment.id %>');
c.addClass('editable');