config/routes.rb
SouthPortSite2::Application.routes.draw do

  root "home#index"
  get "notifications/index"
  get "about", to: 'about#index'
  get "links", to: 'links#index'
  get "links/test", to: 'links#test'
  get "helpful", to: 'helpful#index'
  get "events", to: 'events#index'

  get '/map', to: 'info#map' 
  get '/infolist/:entityName', to: 'info#index' 
  get '/institution', to: 'info#institution', as: :institution
  get '/info/:entityName/:entityId', to: 'info#institution_page', as: :institution_page
  get "notifications", to: 'notifications#index'

  resources :articles, only: [:show, :index]

  resources :comments, only: [:create, :edit, :update, :destroy]

  resources :events

  get "users_profile/:id", to: 'users_profile#show', as: :user

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  namespace :admin do
    resources :articles
    patch '/articles/:id/set_approved', to: 'articles#set_approved', as: :article_set_approved
  end

  post '/tinymce_assets' => 'tinymce_assets#create'

  get "test/index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, as: :commentable

  belongs_to :author, class_name: :User

  scope :approved, -> { where(approved: true).order('id desc') }

  include Notificable
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :set_approved]
  before_action :auth
  before_action :article_auth, only: [:edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = current_user.admin? ? Article : Article.where(author: current_user)
    @articles = @articles.order('date desc')
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.author = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to edit_admin_article_path(@article), notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to edit_admin_article_path(@article) , notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_approved
    approved = params.require(:approved)
    respond_to do |format|
      if current_user.admin? && @article.update(approved: approved)
        format.json { head :no_content }
      else
        format.json { render json: { msg: 'error' }, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :header, :body, :date)
    end

    def auth
      unless current_user
        redirect_to root_url, alert: "Not authorized"
      end
    end

    def article_auth
      article = Article.find(params[:id])
      if !current_user.admin? && article.author != current_user
        redirect_to request.referrer, alert: "You have not enough rights for action"
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.approved
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.order :date
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.haml
- url = @article.persisted? ? admin_article_path(@article) : '/admin/articles'
= form_for(@article, url: url) do |f| 
  - if @article.errors.any? 
    #error_explanation
      %h2= pluralize(@article.errors.count, "error")  + 'prohibited this article from being saved:'
      %ul
        - @article.errors.full_messages.each do |msg| 
          %li= msg

  .field
    = f.label :Название 
    %br
    = f.text_field :title, size: 100  
  
  .field
    = f.label :Дата 
    %br
    = f.datetime_select :date 
  
  .field
    = f.label :Заголовок 
    %br
    = f.text_area :header, class: "tinymce", rel: "tinymce", rows: 4, cols: 60  
  
  .field
    = f.label :Текст 
    %br
    = f.text_area :body, class: "tinymce", rel: "tinymce", rows: 20, cols: 100 

  .actions
    = f.submit 'Сохранить статью'

app/views/admin/articles/edit.html.haml
%section.admin_articles
  %h1 Editing article

  = render 'form'

  = link_to 'Посмотреть результат', @article
  %br
  = link_to 'К списку статей', admin_articles_path

app/views/admin/articles/index.html.haml
%section.admin_articles

  %p.alert= alert
  
  %h1 Список статей

  %table
    %thead
      %tr
        %th Title
        %th Date
        - if current_user.admin?
          %th Approved
        %th
        %th

    %tbody
      - @articles.each do |article|
        %tr
          %td= article.title
          %td= l article.date.try :to_date if article.date
          - if current_user.admin?
            %td= check_box_tag :approved, :approved, article.approved?, data: {url: admin_article_set_approved_path(article)}
          %td= link_to 'Edit', edit_admin_article_path(article), data: {'no-turbolink' => true }
          %td= link_to 'Show', article
          %td= link_to 'Destroy', admin_article_path(article), method: :delete, data: { confirm: 'Are you sure?' } 

  %br

  = link_to 'Новая статья', new_admin_article_path

app/views/admin/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', admin_articles_path

app/views/admin/articles/show.html.haml
%p.notice= notice

%p
  %strong Title
  = @article.title

%p
  %strong Header:
  = @article.header

%p
  %strong>Body:
  = @article.body

%p
  %strong Date:
  = @article.date

= link_to 'Edit', edit_admin_article_path(@article) 
|
= link_to 'Back', admin_articles_path