config/routes.rb
SouthPortSite2::Application.routes.draw do

  root "home#index"
  get "notifications/index"
  get "about", to: 'about#index'
  get "links", to: 'links#index'
  get "links/test", to: 'links#test'
  get "helpful", to: 'helpful#index'
  get "events", to: 'events#index'

  get '/map', to: 'info#map' 
  get '/infolist/:entityName', to: 'info#index' 
  get '/institution', to: 'info#institution', as: :institution
  get '/info/:entityName/:entityId', to: 'info#institution_page', as: :institution_page
  get "notifications", to: 'notifications#index'

  resources :articles, only: [:show, :index]

  resources :comments, only: [:create, :edit, :update, :destroy]

  resources :events

  get "users_profile/:id", to: 'users_profile#show', as: :user

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  namespace :admin do
    resources :articles
    patch '/articles/:id/set_approved', to: 'articles#set_approved', as: :article_set_approved
  end

  post '/tinymce_assets' => 'tinymce_assets#create'

  get "test/index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, as: :commentable

  belongs_to :author, class_name: :User

  scope :approved, -> { where(approved: true).order('id desc') }

  include Notificable
end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
  has_many :contacts, as: :contactable
  has_many :comments, as: :commentable

  def self.icon
    'MapIcons/cinema.png'
  end  

  def self.ru_name
    'Кинотеатры'
  end  

  def self.topic
    'Культура'
  end
end

app/models/cirque.rb
class Cirque < ActiveRecord::Base
  has_many :contacts, as: :contactable
  has_many :comments, as: :commentable

  def self.icon
    'MapIcons/festival.png'
  end

  def self.ru_name
    'Цирки'
  end  

  def self.topic
    'Культура'
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  has_attached_file :picture, 
    styles: { medium: "400x400>"}, 
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :picture, 
    content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def html_text
    text.gsub("\n", "<br/>").html_safe
  end

  def initialize(args=nil)
    super
    self.date = Time.now
    self.votes = 0
  end

  def add_notification(path, user)
    if commentable.respond_to? :add_notification
      commentable.add_notification(self, path, user)
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  scope :phones, -> { where(contact_type: :phone) }

  scope :sites, -> { where(contact_type: :site) }
  scope :social_sites, -> { where(contact_type: :social_site) }
  scope :all_sites, -> { sites + social_sites }
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :contacts, as: :contactable
  has_many :comments, as: :commentable

  def boss_post
    'Главный врач'
  end

  def self.icon
    'MapIcons/hospital-building.png'
  end  

  def self.ru_name
    'Больницы'
  end  

  def self.topic
    'Медицина'
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :file
  validates_attachment_content_type :file, 
    content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/image_path.rb
module ImagePath

  def img_path
    file_name = self.try(:img_file_name) || "#{self.name.gsub(' ', '')}.jpg"
    path = "Objects/#{file_name}"
    File.exists?("app/assets/images/#{path}") ? path : nil
  end
end

app/models/kindergarten.rb
class Kindergarten < ActiveRecord::Base
  has_many :contacts, as: :contactable
  has_many :comments, as: :commentable

  def boss_post
    'Директор'
  end

  def self.icon
    'MapIcons/daycare.png'
  end

  def self.ru_name
    'Детские сады'
  end  

  def self.topic
    'Образование'
  end
end

app/models/library.rb
class Library < ActiveRecord::Base
  has_many :contacts, as: :contactable
  has_many :comments, as: :commentable

  def self.icon
    'MapIcons/book.png'
  end

  def self.ru_name
    'Библиотеки'
  end  

  def self.topic
    'Культура'
  end
end

app/models/notificable.rb
module Notificable 
  def add_notification(comment, path, user)
    users = comments.where.not(user: user).map {|c| c.user}
    auth = try(:author)
    users << auth if auth && user != auth
    users.uniq.each do |u|
      notification = Notification.new( 
        header: "оставил новый комментарий к статье", 
        url: path,
        text: comment.html_text,
        ref_user: u,
        link_title: title
      )
      u.notifications << notification
      notification.save
    end
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :comments, as: :commentable
  include Notificable

  scope :work, -> { find_by name: 'work' }

  def url
    '/links'
  end

  def title
  	name
  end
end

app/models/police.rb
class Police < ActiveRecord::Base
  has_many :contacts, as: :contactable
  has_many :comments, as: :commentable

  def self.icon
    'MapIcons/police2.png'
  end  

  def self.ru_name
    'Полиция'
  end  

  def self.topic
    'Гос. учреждения'
  end
end

app/models/policlinic.rb
class Policlinic < ActiveRecord::Base
  has_many :contacts, as: :contactable
  has_many :comments, as: :commentable

  def boss_post
    'Главный врач'
  end

  def self.icon
    'MapIcons/firstaid.png'
  end    

  def self.ru_name
    'Поликлиники'
  end  

  def self.topic
    'Медицина'
  end
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :contacts, as: :contactable
  has_many :comments, as: :commentable

  include ImagePath

  def boss_post
    'Директор'
  end

  def self.icon
    'MapIcons/school2.png'
  end

  def self.ru_name
    'Школы'
  end  

  def self.topic
    'Образование'
  end
end

app/models/stomatology.rb
class Stomatology < ActiveRecord::Base
  has_many :contacts, as: :contactable
  has_many :comments, as: :commentable

  def boss_post
    'Главный врач'
  end

  def self.icon
    'MapIcons/dentist.png'
  end 

  def self.ru_name
    'Стоматология'
  end  

  def self.topic
    'Медицина'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :notifications

  def new_notifications
    notifications.where(read: false).order("created_at desc") || []
  end

  def old_notifications
    notifications.where(read: true).order("created_at desc") || []
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable

  validates :nickname, uniqueness: { case_sensitive: false }

  def login=(login)
    @login = login
  end

  def login
    @login || self.nickname || self.email
  end

  def self.from_omniauth(auth)
    pp auth
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      nickname = auth.info.nickname.to_s.empty? ? auth.info.name : auth.info.nickname
      email = auth.info.email
      user.nickname = nickname.to_s.empty? ? email : nickname
      user.email = email
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def email_required?
    false
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(nickname) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64290821-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.haml
%footer.mainfooter
  .footer_container
    #city-bg
    #footer-content
      .col
        %nav.main-menu
          %ul
            %li
              %a{href: '/'}
                %i.fa.fa-home.fa-fw
                Главная
            %li
              %a{href: '/about'}
                %i.fa.fa-anchor.fa-fw
                О нас
            - if current_user
              %li
                %a{href: '/admin/articles'}
                  %i.fa.fa-cog.fa-fw
                  Список статей
            %li
              %a{href: '/map'}
                %i.fa.fa-map-marker.fa-fw
                Карта района
            %li
              %a{href: '/helpful'}
                %i.fa.fa-bell.fa-fw
                Куда обращаться
            %li
              %a{href: '/articles'}
                %i.fa.fa-bullhorn.fa-fw
                Новости

      .col
        %nav.reg-log
          %ul>
            %li.registration
              %a{href: '/users/sign_up'} Регистрация
            %li.logon
              %a{ href: '/users/sign_in'} Вход
      .col
        %nav.social-nets
          %ul
            %li.facebook
              %a{ href: 'https://www.facebook.com/groups/Juzhnyj.port/'}
                %i.fa.fa-facebook.fa-fw
            %li.vk
              %a{href: 'https://vk.com/southport_msk'}
                %i.fa.fa-vk.fa-fw
            %li.twitter
              %a{href: 'https://twitter.com/Southport_Msk'}
                %i.fa.fa-twitter.fa-fw
      
      .col.copy
        %img{ src: image_path("anchor-footer.png") }
        %p (c) 2015 г. Гражданское объединение «Южный порт»
        .design-copy KirillDESIGN

app/views/layouts/_header.html.haml
%header#header
  = render 'layouts/login'

  .container.logo
    #logo
      %a{href: "/" }
        %img{ src: image_path("logo.png"), alt: "Лого района (якорь)" }
    .container
      %nav.main.menu.clearfix#menu
        .flexy-menu-wrapper
          %ul.flexy-menu
            %li
              %a{href: "/"}
                %i.fa.fa-home.fa-fw
                Главная
            %li
              %a{href: '/about'}
                %i.fa.fa-anchor.fa-fw
                О нас
            %li
              %a{'href'=> '/map', 'data-no-turbolink' => true}
                %i.fa.fa-map-marker.fa-fw
                Карта района
            %li
              %a{href: '/helpful'}
                %i.fa.fa-bell.fa-fw
                Куда обращаться
            %li
              %a{href: '/articles'}
                %i.fa.fa-bullhorn.fa-fw
                Новости
  

app/views/layouts/_login.html.haml
%nav#sec-nav
  - if user_signed_in?
    %ul
      %li.user-info 
        = link_to "#{current_user.login}", edit_user_registration_path
    %ul
      %li.user-info 
        = link_to "Оповещения (#{current_user.new_notifications.count})", notifications_path
    %ul
      %li.user-info 
        = link_to "Выйти", destroy_user_session_path, method: :delete
  - else
    %ul
      %li.google
        %a{href: omniauth_authorize_path(:user, :Google)}
          %i.fa.fa-google.fa-fw
          &nbsp;
      %li.facebook
        %a{href: omniauth_authorize_path(:user, :facebook)}
          %i.fa.fa-facebook.fa-fw
          &nbsp;
      %li.vk
        %a{href: omniauth_authorize_path(:user, :vkontakte)}
          %i.fa.fa-vk.fa-fw
          &nbsp;
      %li.twitter
        %a{href: omniauth_authorize_path(:user, :twitter)}
          %i.fa.fa-twitter.fa-fw
          &nbsp;
      %li.registration
        %a{href: "/users/sign_up"}
          Регистрация
      %li.logon
        %a{href: "/users/sign_in"}
          Вход

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Гражданское объединение «Южный порт»
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body.front-page
    .page_container
      
      = render 'layouts/header'

      = yield

      = render 'layouts/footer'
      = render 'layouts/analytics'